{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2016-7072",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-7072",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-7072",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://doc.powerdns.com/md/security/powerdns-advisory-2016-03/",
          "name": "https://doc.powerdns.com/md/security/powerdns-advisory-2016-03/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://www.debian.org/security/2017/dsa-3764",
          "name": "DSA-3764",
          "refsource": "DEBIAN",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue has been found in PowerDNS Authoritative Server before 3.4.11 and 4.0.2 allowing a remote, unauthenticated attacker to cause a denial of service by opening a large number of TCP connections to the web server. If the web server runs out of file descriptors, it triggers an exception and terminates the whole PowerDNS process. While it's more complicated for an unauthorized attacker to make the web server run out of file descriptors since its connection will be closed just after being accepted, it might still be possible."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-09-10T17:29Z",
  "lastModifiedDate": "2018-09-11T10:29Z"
}